### ISSUE TITLE
To-Do / Upcoming Features

### ISSUE THREAD

**Issue by asmtilde** [HHS-Coding-Club/acrylicOS#1]
# To-Do
- [ ] Finish loading filesystem in localStorage, then grabbing it from local storage.
- [ ] Better window managing
- [ ] Begin development of the apples (the acrylicOS scripting language)
- [ ] Begin development of quartz (the shell for acrylicOS)
- [ ] Add more system utilities / functions.

**Comment by qqita66** [comment]
---
items:
 - beetbox/beets
 - scottschiller/SoundManager2
 - CreateJS/SoundJS
 - musescore/MuseScore
 - tomahawk-player/tomahawk
 - cashmusic/platform
 - mopidy/mopidy
 - AudioKit/AudioKit
 - Soundnode/soundnode-app
 - gillesdemey/Cumulus
 - metabrainz/picard
 - overtone/overtone
 - samaaron/sonic-pi
display_name: Music
created_by: jonrohan
---
Drop the code bass with these musically themed repositories.
